biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    
    
    path('', views.inicio, name="inicio"),
    path('libros/', views.libros, name="libros"),
    path('autores/', views.autores, name="autores"),
    path('categorias/', views.categorias, name="categorias"),
    path('admin/', admin.site.urls),
    path('biblioteca_app/', include('biblioteca_app.urls')),
]

biblioteca_app/urls.py
from django.urls import path, include
from . import views

app_name = 'biblioteca_app'


urlpatterns = [
	path('index', views.index, name="index"),
    path('formulario', views.formulario, name='formulario'),
	]

biblioteca_app/models.py
from django.db import models

# Create your models here.

class Autor(models.Model):
    nombre = models.CharField(max_length=100)
    nacionalidad = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Libro(models.Model):
    titulo = models.CharField(max_length=200)
    año_publicacion = models.PositiveIntegerField()
    descripcion = models.TextField()
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    categorias = models.ManyToManyField(Categoria)

    def __str__(self):
        return self.titulo

class NavItem(models.Model):
    titulo = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.titulo

biblioteca_app/forms.py
from . import models
from django.forms import ModelForm

class BibliotecaForm(ModelForm):
    class Meta:
        model = models.Libro
        fields = ['titulo', 'año_publicacion', 'descripcion', 'autor', 'categorias']

biblioteca/views.py
from django.shortcuts import render

def inicio(request):
    return render(
        request,
        'inicio.html',
    )

def libros(request):
    return render(
        request,
        'libros.html',
    )

def autores(request):
    return render(
        request,
        'autores.html',
    )

def categorias(request):
    return render(
        request,
        'categorias.html',
    )

biblioteca_app/views.py
from django.shortcuts import render
from .forms import BibliotecaForm
from .models import Libro, Autor, Categoria, NavItem

# Create your views here.

def index(request):
    # Obtener datos necesarios para la página de inicio
    libros_destacados = Libro.objects.all()[:3] 
    jumbotron_info = {
        'titulo': 'Bienvenido a la biblioteca local online',
        'texto': 'Aquí encontrarás una gran colección de libros para leer y disfrutar.',
    }
    nav_items = NavItem.objects.all()

    context = {
        'libros_destacados': libros_destacados,
        'jumbotron_info': jumbotron_info,
        'nav_items': nav_items,
    }
    return render(request, 'biblioteca_app/index.html', context)

def libros(request):
    libros = Libro.objects.all()

    context = {
        'libros': libros,
    }
    return render(request, 'biblioteca_app/libros.html', context)

def autores(request):
    autores = Autor.objects.all()

    context = {
        'autores': autores,
    }
    return render(request, 'biblioteca_app/autores.html', context)

def categorias(request):
    categorias = Categoria.objects.all()

    context = {
        'categorias': categorias,
    }
    return render(request, 'biblioteca_app/categorias.html', context)

def formulario(request):
    form = BibliotecaForm()

    return render(
        request,
        'biblioteca_form.html',
        {'form': form}
    )

biblioteca_app/templates/autores.html
{% extends 'base.html' %}

{% block title %}Autores{% endblock %}

{% block content %}
<div class="container">
  <h1>Catálogo de Autores</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Nacionalidad</th>
      </tr>
    </thead>
    <tbody>
      {% for autor in autores %}
      <tr>
        <td>{{ autor.nombre }}</td>
        <td>{{ autor.nacionalidad }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

biblioteca_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}Biblioteca local{% endblock %}
    <!-- Enlaces a Bootstrap CSS y otros archivos CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- AOS CSS para animaciones de scroll -->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header id="titulo">
      <a href="images/images.png" width="100"></a>
        <h1>Biblioteca Local</h1>
    </header>
    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Biblioteca Local</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url "inicio" %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "biblioteca_app:index" %}">Biblioteca_app</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="libros">Libros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="categorias">Categorias</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="autores">Autores</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>

    <div class="jumbotron">
      <div class="container">
        <h1 class="display-4">{{ jumbotron_info.titulo }}</h1>
        <p class="lead">{{ jumbotron_info.texto }}</p>
        <hr class="my-4">
      </div>
    </div>
    <!-- Contenido específico de cada página -->
    {% block content %}
    {% endblock content %}

    <p>Más información sobre la biblioteca:</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Visitar</a>

    <!-- Pie de página -->
    <footer class="footer">
        <div class="container">
            <span class="text-muted">© 2024 Biblioteca Local</span>
        </div>
    </footer>

    <!-- Enlaces a Bootstrap JS y otros archivos JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <!-- SweetAlert JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- AOS JS para animaciones de scroll -->
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.3.4/dist/aos.js"></script>
</body>
</html>

biblioteca_app/templates/biblioteca_app/index.html
{% extends 'base.html' %}

{% block content %}




{% endblock %}

biblioteca_app/templates/biblioteca_form.html
{% extends 'base.html' %}

{% block content %}
    <form
        action="{% url 'biblioteca_app:formulario' %}"
        method='post'>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Enviar"/>
        
{% endblock content %}

biblioteca_app/templates/categorias.html
{% extends 'base.html' %}

{% block title %}Categorias{% endblock %}

{% block content %}
<div class="container">
  <h1>Categorías de Libros</h1>
  <ul class="list-group">
    {% for categoria in categorias %}
    <li class="list-group-item">{{ categoria.nombre }} - {{ categoria.descripcion }}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

biblioteca_app/templates/inicio.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% load static %}

{% block content %}
<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static "images/1.jpg" %}" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5>FOTO 1</h5>
        <p>{% lorem 1 b random %}</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static "images/2.jpg" %}" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5>FOTO 2</h5>
        <p>{% lorem 9 w random %}</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static "images/3.jpg" %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>FOTO 3</h5>
        <p>{% lorem 1 b random %}</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock content %}

biblioteca_app/templates/libros.html
{% extends 'base.html' %}

{% block title %}Libros{% endblock %}

{% block content %}
<div class="container">
  <h1>Catálogo de Libros</h1>

  <a href="{% url "biblioteca_app:formulario" %}">Agregar Libro</a>

  <table class="table">
    <thead>
      <tr>
        <th>Título</th>
        <th>Año de Publicación</th>
        <th>Descripción</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for libro in libros %}
      <tr>
        <td>{{ libro.titulo }}</td>
        <td>{{ libro.año_publicacion }}</td>
        <td>{{ libro.descripcion }}</td>
        <td><a href="{% url 'detalle_libro' libro.id %}" class="btn btn-sm btn-primary">Ver más</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}